### ISSUE TITLE
Update Posts Style

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#1]
Use frame as guide
https://framer.com/projects/Geeks-Day--bO8SQKOvAHeyGXKGpFvi-4ogpk

**Comment by Jhonproyec** [comment]
I worked on updating the view of the posts.
I made the post responsive, it has a maximum width of 700 pixels, so that the cards don't look too big.
I implemented the like and comment buttons.
The like button is still incomplete, and also the text where the likes of the post are displayed.
Completion time approximately 5 hours.
I had problems with the like button, since I did not know how to capture the click event to show a new like on the screen, and change the color of the button.
I had to investigate to be able to make the page responsive and be able to implement it.

**Comment by Jhonproyec** [comment]
I worked on changing the text color of the Like button when the post receives likes.
I was researching in the documentation how to catch the click event, but I couldn't change the color of the text, I did more research on the like_button library to find another solution and I was able to find and implement it in the post.
Completion time approximately 4 hours.

**Comment by GuateGeeks** [comment]
Style needs to be improved
- Buttons will have the same spacing from borders and be centered
- Buttons size will change if necessary on large and small screens.
- Both Buttons will have the same size 

On my phone
Buttons will have the same spacing from the border and will be centered.
![WhatsApp Image 2021-08-12 at 12 17 42 PM](https://user-images.githubusercontent.com/88637709/129248249-0c6b5304-0516-4c32-9ec5-ce4cb63e5a06.jpeg)

On my browser
Buttons will have the same spacing from the border and will be centered.
![2021_08_12_12_17_00_GeeksDay_Brave](https://user-images.githubusercontent.com/88637709/129248335-5a906baf-07d7-4bef-956a-f9f6815a0f17.png)

**Comment by GuateGeeks** [comment]
Buttons implementation is too long, probably better to break it into like and comment button, on separated classes or functions.

https://github.com/GuateGeeks/GeeksDayFlutter/blob/development/lib/ui/post/cards/button_widget.dart

**Comment by GuateGeeks** [comment]
Please add comments on your code.

**Comment by Jhonproyec** [comment]
I worked on integrating a new screen to show the full image shown in the post
realization time approximately 2 hours

**Comment by Jhonproyec** [comment]
I updated the style of the buttons making them adapt to any device.
I also left both buttons the same size,
I created a function for each button, to separate the code and to make it more understandable, I puted comments indicating what the functions are for.
Completion time 3 hours approximately

**Comment by Jhonproyec** [comment]
I added more spacing to the sides of the buttons so there wasn't much space in between, I made sure the buttons looked good on different screen sizes.
Completion time approximately 30 minutes.

**Comment by Jhonproyec** [comment]
I worked on implementing the time when a new post is published
completion time approximately 4 hours.
I had to do  research on the DateTime function in flutter, as the recommended documentation only showed the time the post was published. I had to read the code well to know how to extract the date of the post from the database.
I implemented the necessary logic to show how long a new post has been published.

**Comment by Jhonproyec** [comment]
I worked on creating the preview of the images of the post and the quiz, I had problems showing the images and I had to investigate to solve the problem, I was also checking how I could upload the images to the database but for now the images cannot be uploaded.
Completion time approximately 4 hours
