### ISSUE TITLE
Improve buttons tap area

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#108]
The following items needs to be improved, now tap only works on icons
-  Menu items
- New Post
- New Quiz
- Menu de Configuracion

Remove tap animation on "Comentarios" page
- Like button
- Send message button

**Comment by Jhonproyec** [comment]
I worked on removing the animation of the button to open the configuration page, since it still had the animation.
completion time approximately 1 hour
I had to copy the comment redesign code again since it hadn't been merged with the development branch.
