### ISSUE TITLE
Miscellaneous fixes

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#113]
- [x] Utilizar mismo margen de registrate
- [x] Boton de agregar evento debe de ser el mismo color del tema
- [x] Intercambiar iconos de like y comentarios con contenido del post, agregar espacios apropiados ver diseño
- [x] Hay que alineaer el nombre y la hora con el avatar
- [x] Hay que alienear el kebab menu de los posts
- [x] Separar texto de iconos en el menu
- [x] Cambiar texto user a Perfil
- [x] Revisar tamaños de iconos
- [x] Comentarios, revisar Hay que alineaer el nombre y la hora con el avatar y tamaños.
- [x] Ajustar colores comentarios
- [x] Estandarizar todos los textos a Biriyani excepto el menu que sera Abel
- [x] Ajustar colores de sliders "switch"
- [x] Hamburger menu necesita padding derecho

**Comment by adawolfs** [comment]
@Jhonproyec please update here when a task is completed, you can probably use this ticket to log all the effort.

**Comment by Jhonproyec** [comment]
I worked on aligning the texts and the buttons in the posts and comments, I also removed the hover effect from the buttons, completion time approximately 3 hours

**Comment by Jhonproyec** [comment]
I worked on adjusting the button margins, since in the Web app they did not fit well, it took me a long time to check that the margins were correct because I had to wait for the changes to be shown in github pages
completion time approximately 3 hours
