### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#13]
Design and Implement a user profile page 

![Texto](https://pro2-bar-s3-cdn-cf.myportfolio.com/e7604dd7c0b97c17b564048e87069b7f/b9878d47-731e-47c5-8246-c866fbf457cc_rw_1200.png)

**Comment by Jhonproyec** [comment]
I worked on designing and creating the user profile, I had problems to lay out the background of the page, since on the desktop screen it covers all the space, and reducing it does not look very good.
Completion time 4 hours approximately
