### ISSUE TITLE
Implement Drawer

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#14]
https://api.flutter.dev/flutter/material/Drawer-class.html

Add Options
- Profile
- Settings
- Logout

**Comment by Jhonproyec** [comment]
I worked on implementing the drawer or dropdown menu in the app. I had problems with the responsive as it is displayed from the side of the screen.
Completion time approximately 1 hour and 30 minutes.

**Comment by Jhonproyec** [comment]
I worked on implementing the side menu differently than the app in desktop view, I implemented it by making the menu see only inside the main container where posts are viewed, but it looked bad as the menu creates a background when it is implemented and does not look good as the background is seen only in the main container part and does not apply to the whole screen. I decided to leave the menu as previously implemented, I reported it to see if there was a need to change the desktop screen menu layout. realization time 2 hours and 30 minutes
