### ISSUE TITLE
Create view for event registration

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#25]
Users should be able to register into a event using a code

https://flutterfix.com/how-to-use-the-flutter-gridview-count-gridview-extent/

**Comment by Jhonproyec** [comment]
I worked on the implementation of the event log view, generating the event cards and taking them to the main view after clicking.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on programming the button to show the cards where you can see the information of the event, also when you click on one of the cards it takes you to the publications of the corresponding event
Completion time 2 hours and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on implementing the dark theme in the event log view, I had problems with the implementation since when changing to the light theme the changes are not made in the log view.
Completion time 2 hours and 30 minutes approximately
