### ISSUE TITLE
Trigger post list update

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#31]
https://www.youtube.com/watch?v=ORApMlzwMdM

**Comment by Jhonproyec** [comment]
I worked on the integration of the refreshIndicator, I was investigating how to make the post update, but I could not solve it, I tried to do it by refreshing the page but when it was updated only the posts appeared, and the button to create a new post did not appear, or the button to open the menu.
Completion time 2 hours and 30 minutes approximately

**Comment by Jhonproyec** [comment]
Trabajé en implementar el refreshIndicator de la manera que me recomendaron, pero solo agregaba los posts existentes, lo reporté y dejamos la implementación pendiente.
Tiempo de realizacion 2 horas aproximadamente

**Comment by adawolfs** [comment]
Al actualizar el list, los post se estan duplicando

**Comment by Jhonproyec** [comment]
I worked on updating the posts by adding a refreshIndicator, so the user only has to slide the screen down for the posts to be updated.
Time of realization 1 hour approximately
