### ISSUE TITLE
Implement Loader for Flutter App

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#33]
A loader is required to indicate the user that the page is "working"
Options:
1. Make it on html at the web/index.html and detect when flutter is ready (But how!?)

**Comment by adawolfs** [comment]
https://github.com/flutter/flutter/pull/81581/files

**Comment by adawolfs** [comment]
https://github.com/flutter/flutter/issues/77936

**Comment by Jhonproyec** [comment]
I worked on the implementation of the loader, I had problems with the routes and with the login of the users, I reported it in today's meeting and there are some improvements to be made in the loader.
Completion time 2 hours and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on the implementation of the loader changing the previous design and making the corrections that were explained to me in the meeting.
completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on correcting the error to show the loader in github pages, I also adjusted the size of the image so that it does not look too large on the desktop, completion time approximately 45 minutes
