### ISSUE TITLE
Update Create Post Style

### ISSUE THREAD

**Issue by GuateGeeks** [GuateGeeks/GeeksDayFlutter#4]

**Comment by Jhonproyec** [comment]
I worked on adding a modal to add a new post, I put in the input the option to search for an image from the gallery to be able to upload it,
I had problems loading a preview of the image, but those errors will be fixed later.
I left commented the code that serves to show the preview of the image, we only need to make tests that the image is shown well in the preview.
completion time 3 hours approximately

**Comment by Jhonproyec** [comment]
I worked on uploading the images to the firestore when a post was created, I had problems when trying to upload the images through the libraries that were exported, I requested a meeting to be able to solve it and in the meeting the problem was resolved.
Completion time 5 hours approximately
