### ISSUE TITLE
adjust the size of the loader image

### ISSUE THREAD

**Issue by Jhonproyec** [GuateGeeks/GeeksDayFlutter#40]
the loader image when starting the application is shown in a small size, then it is shown in a larger size

**Comment by Jhonproyec** [comment]
I worked on the implementation of the button to scroll to the top when the user has dropped a lot in the view of the posts.
The images are not being shown for now, I hid them to be able to see the operation of the button, since every time I scrolled the images were reloaded.
completion time approximately 3 hours

**Comment by Jhonproyec** [comment]
I removed the low-resolution image in the loader, I'm loading the image from the web folder to see if this solved the problem with the loader on mobile. Completion time approximately 1 hour and 30 minutes

**Comment by adawolfs** [comment]
What is missing here?

**Comment by adawolfs** [comment]
@Jhonproyec please check

**Comment by Jhonproyec** [comment]
The image had already been changed, because the previous one did not look good, in the browser in desktop mode the image looks good, in mobile mode the image looks small and then it becomes large.
