### ISSUE TITLE
Change user reference

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#42]
Post will have only the userid reference, and all the data should be retrieved from firebase user collection

**Comment by Jhonproyec** [comment]
I worked on changing the user's reference to the posts, to bring the image and the name from the user collection, completion time approximately 3 hours

**Comment by Jhonproyec** [comment]
I worked on changing the user's reference in the posts.
When the user updates his profile, these changes are reflected in the posts.
Completion time 2 hours and 30 minutes approximately
