### ISSUE TITLE
Go to top Button

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#49]
After scrolling a button to return to the top should be shown

**Comment by adawolfs** [comment]
Hello Jonatan, could you please add the time spent on this task?

I see a lot of commented code here, probably something you was working on, please try to avoid it.
https://github.com/GuateGeeks/GeeksDayFlutter/commit/cfd3d4df0d1e623b126922f45cb65822018b0097#diff-6a495284bc6fee079041a1a508da7d2fffbee4c2cdae55ae35eadc57e17322afR24

**Comment by Jhonproyec** [comment]
I worked on the implementation of the button to scroll up when the user has seen several posts, I commented on the code to show the images since each time I scrolled the images were reloaded and did not show well, completion time 1 hour and 30 minutes approximately
