### ISSUE TITLE
Update posts on real time

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#56]
Posts should be updated on real time, use whatsapp implementation as reference.

https://github.com/amirk3321/whatsApp_clone/blob/master/lib/presentation/bloc/my_chat/my_chat_cubit.dart#L17

**Comment by Jhonproyec** [comment]
I worked on displaying the posts in real time, using the suggested repository as a reference, completion time 2 hours and 30 minutes approximately

**Comment by Jhonproyec** [comment]
I worked on the implementation to show the posts created without having to reload the page to the other users, implementing sockets. completion time approximately 4 hours

**Comment by Jhonproyec** [comment]
I worked on the implementation to display the posts in real time, the implementation is already working, but at the moment I have commented code and test files. The posts are being shown in all the events, I need to do the validation so that the posts can be shown in their respective event.
Time of realization 3 hours approximately

**Comment by Jhonproyec** [comment]
implementing the functionality to show the posts in an orderly way and for each event, I realized that when creating an event the other events were duplicated, but when viewing the application in a different window to see the changes in real time, the post was added correctly , I am going to work on implementing the new view for posts according to the new design to resolve that error.
Time of realization 3 hours approximately

**Comment by Jhonproyec** [comment]
I worked on correcting the error that when creating a new post the posts were repeated, now when creating a post it is shown and the other posts are not repeated, completion time approximately 2 hours.
