### ISSUE TITLE
Change StreamBuilder implementation for post images.

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#57]

**Comment by Jhonproyec** [comment]
I worked on using the implementation to save the routes of the images of the posts in the database, so it will avoid using streambuilder to obtain them, and avoid reloading the images when scrolling, completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on showing the images and validating if there is no image in the post, only showing a container.
Time of realization 1 hour approximately

**Comment by Jhonproyec** [comment]
I changed the streambuilder to display the images, and did the validation so that the post displays correctly when it contains no image.
completion time approximately 1 hour
