### ISSUE TITLE
Evaluate video posting

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#58]
Evaluate the possibility about post videos.

**Comment by Jhonproyec** [comment]
I was researching and there is a library called imagepicker where it accepts uploading videos and images, completion time approximately 1 hour

**Comment by adawolfs** [comment]
How much effort do you estimate to make it done with firebase on our app?

**Comment by adawolfs** [comment]
Jonatan says its about 5h

**Comment by adawolfs** [comment]
Will be implemented on #123
