### ISSUE TITLE
Design and Implement "Post -> Likes" Relationship

### ISSUE THREAD

**Issue by GuateGeeks** [GuateGeeks/GeeksDayFlutter#6]

**Comment by adawolfs** [comment]
@Jhonproyec Actualiza tu codigo y verifica que la funcionalidad este funcionando correctamente.

**Comment by Jhonproyec** [comment]
I reviewed the code to know and know how the like logic works, I also did the tests and the button works correctly.
Completion time approximately 20 minutes

**Comment by Jhonproyec** [comment]
I worked on solving the Like button issue as the post could only like when the heart of the Like button was pressed and not the button.
Time of realization 3 hours approximately.
I read the documentation for the like_button to see if a background color and fill could be applied so as not to use the ElevatedButton, but it couldn't, so I did several tests to see which was the most optimal solution and that there wasn't much code rewritten, at the final I just assigned some parameters in the onPressed and thus I solved the problem
