### ISSUE TITLE
Rediseño de Login y Registro

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#60]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by Jhonproyec** [comment]
I started redesigning the application, adjusting the colors and text in the light theme.
completion time approximately 1 hour

**Comment by Jhonproyec** [comment]
I worked on the redesign of the form to enter the application and to register, I had problems overlaying a button on the card that contains the form.
completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on the redesign of the login and registration form, I had problems changing the input text at the time of writing, since the text looked light gray, I had to investigate how I could solve that problem, completion time 3 hours about

**Comment by adawolfs** [comment]
Please fix the design:
![WhatsApp Image 2022-01-24 at 1 09 17 PM](https://user-images.githubusercontent.com/7836423/150848188-d9ee6459-560f-42c4-9e66-9b1c5ddac549.jpeg)

**Comment by adawolfs** [comment]
Utilizar color #4A4A4A para la palabra Iniciar Sesion y Registrate

**Comment by Jhonproyec** [comment]
I worked on redesigning the registration form, I had problems with the button to save the record, when I put the button as it is in the design when you clicked the button it did not respond, I was investigating why that happened, but at the time of leaving it inside the card the button if it saves the data. I started to integrate my eyes on the login form. completion time 2 hours and 30 minutes

**Comment by Jhonproyec** [comment]
I adjusted the image in the login form and solved the problem with the registration button to place it at the bottom of the form. realization time 1 hour approximately

**Comment by adawolfs** [comment]
![Screenshot_2022-02-02-22-23-53-76_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/7836423/152281073-859a66ee-7aa7-49b0-910f-ed42d7ed117f.jpg)

Please investigate how to avoid this behavior, 

The button should keep it's position when keyboard is open

**Comment by Jhonproyec** [comment]
I worked on correcting the responsive of the form on mobile screens, since when opening the keyboard the buttons did not show well, I added the image to the registration form.time of realization 1 hour approximately
