### ISSUE TITLE
Rediseño de pagina de eventos

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#61]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by adawolfs** [comment]
Depends on #75

**Comment by Jhonproyec** [comment]
I worked on the redesign of the events screen, I modified the files to save the image path in the database, and thus prevent the images from being reloaded every time the user enters the events screen.
when creating an event an error appears, but that error will be solve when ticket #75 is made
Completion time approximately 1 hour and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on the implementation to show the events without reloading, and so that the images do not reload when returning to the events page. completion time 3 hours and 30 minutes approximately

**Comment by Jhonproyec** [comment]
I worked on the implementation so that the user can be added to an event, but I had a problem when editing the event, since when the user registers, a loop is created in the database, registering the user, I was investigating how resolve this error, completion time approximately 3 hours

**Comment by Jhonproyec** [comment]
I worked on the implementation so that the user can join the events, I managed to solve the loop error in the database, but now the data that is entered suddenly gets deleted and added again, I am looking for the most optimal way to loop through all the events and do the validation to add the user to the event. completion time approximately 3 hours

**Comment by adawolfs** [comment]
@Jhonproyec have you added a commit for your last update?

**Comment by Jhonproyec** [comment]
I worked on the implementation so that the user can register for the event and be able to see the posts, like and comment.
completion time approximately 2 hours.

**Comment by Jhonproyec** [comment]
I worked on finishing the redesign of the events page, I also verified that events could be created and that users could join an event. completion time 1 hour with 10 minutes approximately
