### ISSUE TITLE
Creacion de menu inferior

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#63]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by Jhonproyec** [comment]
I worked on the implementation of the bottom navigation menu, at first I used the widget to create a bottom menu, but I had problems wanting to show the modal to create the posts, so I had to research and see how else I could make a lower navigation menu. in the end I created it with a bottomAppbar.  Completion time 2 hours and 30 minutes approximately

**Comment by adawolfs** [comment]
The navbar is being cutted when its loaded as a webapp

**Comment by Jhonproyec** [comment]
I added a margin at the bottom of the button so the text doesn't get cut off. completion time approximately 20 minutes

**Comment by adawolfs** [comment]
El margen agregado es muy grande, los textos deben de ser mas pequeños

![2022-01-26 22_42_26-GeeksDay - Brave](https://user-images.githubusercontent.com/7836423/151293314-e3cb4699-d967-4bba-bed7-23795b5a98fe.png)

**Comment by Jhonproyec** [comment]
I corrected the margin and the text of the menu, completion time approximately 20 minutes, I did tests with different browsers, since in the browser I use (edge) the menu looked fine with the margin that I had added.

**Comment by adawolfs** [comment]
la fuente a utilizar en el menu es https://fonts.google.com/specimen/Abel
Y para el resto de textos https://fonts.google.com/specimen/Biryani

**Comment by adawolfs** [comment]
import icons from figma, please take in count the suggested size for each option

**Comment by Jhonproyec** [comment]
I worked on improving the bottom navigation menu, I used the font as it is in the design and I used the same icons, I centered the text and icons, I had problems wanting to push to the branch where I am saving the changes from the bottom menu, so I had to take the changes to the development branch to be able to upload them,  realization time approximately 3 hours

**Comment by Jhonproyec** [comment]
when viewing the application in the browser in the menu the icons were not showing, I worked on solving that problem, the problem was with the paths, I had to write the full path in the pubspec to make it work. Completion time 1 hour and 45 minutes approximately
