### ISSUE TITLE
Rediseño creacion de nuevo post

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#64]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by Jhonproyec** [comment]
I started working on the new design of the view to create the posts, completion time approximately 1 hour and 30 minutes

**Comment by Jhonproyec** [comment]
I worked in the modal to select if you want to create a post or a quiz, completion time approximately 1 hour.
There is commented code in the create post file, because it is not finished yet.

**Comment by Jhonproyec** [comment]
I worked on the implementation to create the posts.
I had problems showing the preview of the images, since it shows me an error that I am not calling the cubit correctly, but then it shows me the preview of the image.
completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on implementing the functionality to create the posts, a preview of the selected image is already being shown, I need to do the validation to save the post with the event id. realization time 2 hours approximately

**Comment by Jhonproyec** [comment]
I worked on the implementation to create post, you can already create the posts, I need to add an indicator to let the user know that the post is being created. realization time 1 hour approximately

**Comment by Jhonproyec** [comment]
I worked on implementing a circularProgressIndicator when the user saves a new post, but it is not shown at the time of creating the post, I was reviewing how to handle the states to be able to show it. I also changed the color of the input in dark mode, realization time 2 hours approximately

**Comment by Jhonproyec** [comment]
I finished designing the post view, I focused on finishing the redesign and then adding the missing details, completion time approximately 1 hour and 30 minutes
