### ISSUE TITLE
Rediseño creacion de nuevo quiz

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#65]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by Jhonproyec** [comment]
I worked on the redesign of the quiz creation view. completion time 1 hour and 30 minutes approximately

**Comment by Jhonproyec** [comment]
I worked on the functionality to create the quiz, completion time 1 hour approximately

**Comment by Jhonproyec** [comment]
I worked on implementing the logic to create the post, since I am migrating everything to a single file, I added a library for the switch button that resembles the design button, completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
i am working on moving the logic to a single file to create the quizzes, all the functions will be in the cubit feed file
completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on the implementation of routes, I was investigating to obtain a post by id to be able to show the comments and the image when clicking on it. completion time 2 hours

**Comment by Jhonproyec** [comment]
I worked on the implementation of the quizzes, I had problems getting the answers written in the input, I was reviewing the previous implementation to solve the problem completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on the quiz implementation, the buttons to enter the answers are already being generated dynamically, the image is being loaded and it is being handled from a single file, I am having problems when I want to save the information in the database data, since I am not obtaining the information entered in the inputs, completion time 1 hour and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on the implementation to publish the quiz, completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on the implementation of the quiz, I still have a problem with saving the answers in the database since when generating a new entry it saves what the input brings, completion time approximately 3 hours

**Comment by adawolfs** [comment]
Fixed!
