### ISSUE TITLE
Rediseño menu de configuracion

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#68]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by Jhonproyec** [comment]
I worked on the redesign of the settings page, adding the option to change the theme of the application and the option to exit. realization time1 hour approximately

**Comment by adawolfs** [comment]
Please fix with 
https://github.com/GuateGeeks/GeeksDayFlutter/issues/62#issuecomment-1020438279

**Comment by Jhonproyec** [comment]
I worked the change of colors of the text and icons of the screen settings, time of realization 30 minutes approximately
