### ISSUE TITLE
Reload feed is not working

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#69]
After reviewing ticket #56 I did notice that reload action is not working

**Comment by adawolfs** [comment]
Is it done?

**Comment by Jhonproyec** [comment]
the refresh indicator is working, since the time is updated, the likes and comments are not updated because they are being displayed from the post_cubit file.
I worked on implementing the likes function in the feed_cubir file, completion time 2 hours

**Comment by adawolfs** [comment]
@Jhonproyec is it done?

**Comment by Jhonproyec** [comment]
The functionality to reload the feed is working, only the changes were not shown because the likes and comments buttons were being called from another state.
