### ISSUE TITLE
Create a proper error handler on login

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#72]
Erros should be catched and properly managed

Right now its shown as follows:
![2022-01-17 17_27_40-Meet - zdq-giwy-itf - Brave](https://user-images.githubusercontent.com/7836423/149847366-7c577e6f-8628-4b89-b194-e6a556be5689.png)

Use this image as reference for better implementation
https://forum.radzen.com/uploads/default/original/2X/8/84bb18eb7a38fd79688cdd43902058cdb0620426.png

**Comment by Jhonproyec** [comment]
I worked on showing the errors in the registration form, I was investigating the most optimal way to do it, and at the moment I found the one that is implemented, I still need to add the card to show the error as suggested in the image completion time 2 hours about

**Comment by adawolfs** [comment]
We can just set red text bellow the inputs and later think about specific solutions.
