### ISSUE TITLE
Implement GuateGeeks Icon

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#73]
The web app should have his own web icon

Please investigate how to make it done properly
- Web ico
- Webapp icon
- Webapp on open slash

**Comment by Jhonproyec** [comment]
I worked on researching and implementing the logo in the navigation tab and displaying the logo when it is added as a web app on mobile. Realization time 2 hours approximately

**Comment by adawolfs** [comment]
Tested and approved!

**Comment by Jhonproyec** [comment]
I worked on changing the logo of the favicon and the web app icon. realization time 1 hour approximately, I had problems with the implementation of the svg, but researching I managed to solve it
