### ISSUE TITLE
Design Quizz integration

### ISSUE THREAD

**Issue by GuateGeeks** [GuateGeeks/GeeksDayFlutter#9]
Use https://github.com/Akashdu/FlutterQuizzApp as reference.

**Comment by Jhonproyec** [comment]
I worked in the view to create a post with questions and answers and those who enter the application can answer or select the correct answer from the post.
I had as a reference the design and the recommended code, but there are functions that are already obsolete for the version of flutter that is being used to create the application.
Completion time 5 hours to approximately

**Comment by Jhonproyec** [comment]
I worked on modifying the design of the Quizz in the main view, I also added buttons so that the user can create a Quizz from the same modal to create a new post.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I changed the color of the modal buttons to change pages, and fixed the responsive view of creating new Quizz.
Added comments for buttons not working well
Completion time approximately 1 hour.

**Comment by Jhonproyec** [comment]
I worked on changing the color of the icon that is in the input to select which is the correct answer of the questionnaire, I also added a tooltip to show a message when the user hovers the mouse over the icon.
completion time 1 hour and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on the button implementation to generate new inputs for the Quizz responses.
I have been researching to be able to do it in the best way.
completion time approximately 1 hour

**Comment by Jhonproyec** [comment]
I worked on creating the inputs dynamically.
The button to create more inputs is already programmed, it only remains to be implemented in the modal where the quiz is created, but I had several problems to be able to display it. Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on solving the error that was shown when wanting to show the button to add more response entries to the Quizz. The error no longer appears, but does not show the new entries that are dynamically created

**Comment by Jhonproyec** [comment]
I worked on solving the problem of generating inputs dynamically from the application view.
I worked on implementing the button to know which is the correct answer in the questionnaire.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on selecting the answer of the quiz and showing which is the correct answer, and the selected answer. completion time approximately 3 and a half hours

**Comment by Jhonproyec** [comment]
I worked on the implementation of marking the icon of the correct answer in green, I had problems with changing the color of the icon, and in the meeting the problem was solved, completion time approximately 1 hour and thirty minutes

**Comment by Jhonproyec** [comment]
I worked on the responsive design of the response progress bar.
I had a problem when centering the progress bars, since they were not centered with the center widget, or Column and the CrossAxisAlignment property, in the end I defined each progress bar within a Row and so I could center them and make them adapts to any type of device
Completion time, 1 hour and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on adding the information from the answers to the database
Time of realization 2 hours to approximately

**Comment by Jhonproyec** [comment]
I worked on the implementation of the quizz to save the answers to the questions.
I also began to see how to implement the logic so that the percentages of the selected answers in the quizz are displayed. completion time 1 hours and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on adding the answers from the quiz to the database, I started doing what was suggested, just calling a function that was already created and thus being able to send the answers from the form to the database, but I was not saving them, so I had to find another solution to be able to save the answers to the database.
Completion time 3 hours and 30 minutes

**Comment by Jhonproyec** [comment]
Trabajé en la creación de una nueva colección en la base de datos para mantener registros de los usuarios cuando respondían un cuestionario.
Creé el modelo, el servicio y el bloque, traté de obtener la información de la base de datos pero en el momento que quieres mostrarla en la consola me mostró un error que el contexto no contiene quizrecordsCubit, traté de hacer el implementación como se hizo con el administrador, pero aún me mostraba el mismo error.
Tiempo de finalización aproximadamente 5 horas.

**Comment by Jhonproyec** [comment]
I worked on implementing the function to save the results of the users with the quizz.
This saves in the database the user id, the post id, the selected answer and if he answered correctly, or if he answered badly.
In today's meeting it was possible to correct the error that I had with the BlocProvider

**Comment by Jhonproyec** [comment]
I worked on disabling the answers after the user chose their answer from the quiz.
I had problems uploading user data to the database, but I was able to solve it by reading the code in the posts. completion time 3 hours and 30 minutes approximately

**Comment by Jhonproyec** [comment]
I worked on editing the count in the database, of the people who answered the quiz.
I had problems at the beginning but I followed the recommendation to edit the entire array, to edit the necessary field, completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on showing the percentages of the selected answers from the quiz, but I had problems to show the independent data in the progressbar, I decided to change it and show some cards as buttons and that the border would change color when it is selected, I was working on how to change the color only to the one selected, but for some reason all the buttons change color, completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
create a new branch where the progress indicator is shown in the quiz, to be able to work the logic to show the percentages of the answers. completion time approximately 45 minutes

**Comment by Jhonproyec** [comment]
I worked on implementing the quiz functionality, showing the percentage of users who have selected the answers, also adding a validation if the user has already answered the quiz and cannot choose another answer.
completion time 3 hours approximately
