### ISSUE TITLE
Bug when a new post is added

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#96]
When a new post is created sometimes its added to the feed with prefilled like and comment numbers, it seems like its getting the same values of previous last post, like if the values are not properly cleaned or the ui is not getting the update... 

Probably that part is not updated by flutter on render events?

When you scroll down and then scroll up to get back to top the values are properly shown.

**Comment by Jhonproyec** [comment]
I worked on solving the bug when creating the post, in the count of likes and comments it was not updated because they had a different status than the one of creating post.
Completion time 1 hour and 20 minutes approximately
