### ISSUE TITLE
Comment count is not updated when comments are deleted.

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#97]
https://github.com/GuateGeeks/GeeksDayFlutter/blob/development/lib/bloc/posts/post_cubit.dart#L161 should implement https://github.com/GuateGeeks/GeeksDayFlutter/blob/development/lib/bloc/posts/post_cubit.dart#L152 

or probably we can just count the comments every time??

**Comment by Jhonproyec** [comment]
I worked on solving the comment counter bug, the error was due to the fact that the status of the post was not being passed correctly to update the counter in real time, completion time approximately 2 hours
